# Generated by Django 5.2 on 2025-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('sdate', models.DateField()),
                ('ldate', models.DateField()),
            ],
        ),
    ]
