# Generated by Django 5.2 on 2025-04-27 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_profiles_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('yesno', models.CharField(blank=True, default='no', max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
            ],
        ),
    ]
